-- Migration: Add missing airports and populate hangar listings
-- Description: Add Sudeste and Centro-Oeste airports + sample hangar data

-- First, add missing airports
INSERT INTO airport_icao (icao_code, iata_code, airport_name, city, state, country, latitude, longitude, is_public, has_facilities) VALUES
('SBGL', 'GIG', 'Rio de Janeiro/Galeão - Antônio Carlos Jobim', 'Rio de Janeiro', 'RJ', 'Brasil', -22.809999, -43.250557, true, true),
('SBBH', 'PLU', 'Belo Horizonte/Pampulha - Carlos Drummond de Andrade', 'Belo Horizonte', 'MG', 'Brasil', -19.851389, -43.950556, true, true),
('SBBR', 'BSB', 'Brasília/Presidente Juscelino Kubitschek', 'Brasília', 'DF', 'Brasil', -15.869167, -47.920834, true, true),
('SBGO', 'GYN', 'Goiânia/Santa Genoveva', 'Goiânia', 'GO', 'Brasil', -16.631944, -49.220833, true, true),
('SBCG', 'CGR', 'Campo Grande/Internacional', 'Campo Grande', 'MS', 'Brasil', -20.468611, -54.672500, true, true)
ON CONFLICT (icao_code) DO UPDATE SET
  airport_name = EXCLUDED.airport_name,
  city = EXCLUDED.city,
  state = EXCLUDED.state,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  is_public = EXCLUDED.is_public,
  has_facilities = EXCLUDED.has_facilities,
  updated_at = CURRENT_TIMESTAMP;

-- Create 5 sample hangar listings
-- Note: Replace owner_id with actual user IDs from your database
-- For demo purposes, we'll use user_id = 1 (you may need to adjust this)

INSERT INTO hangar_listings (
  owner_id,
  icao_code,
  aerodrome_name,
  city,
  state,
  country,
  hangar_number,
  hangar_location_description,
  hangar_size_sqm,
  max_wingspan_meters,
  max_length_meters,
  max_height_meters,
  accepted_aircraft_categories,
  hourly_rate,
  daily_rate,
  weekly_rate,
  monthly_rate,
  available_from,
  available_until,
  is_available,
  operating_hours,
  services,
  description,
  special_notes,
  accepts_online_payment,
  accepts_payment_on_arrival,
  photos,
  status
) VALUES 
-- 1. São Paulo/Congonhas
(
  1,
  'SBSP',
  'São Paulo/Congonhas',
  'São Paulo',
  'SP',
  'Brasil',
  'H-12A',
  'Hangar próximo ao pátio de aviação geral, lado oeste do aeroporto',
  120.00,
  15.00,
  12.00,
  5.50,
  '["monomotor", "bimotor", "executive"]'::jsonb,
  NULL,
  250.00,
  1500.00,
  5500.00,
  CURRENT_DATE,
  (CURRENT_DATE + INTERVAL '1 year'),
  true,
  '{"monday": {"open": "06:00", "close": "22:00"}, "tuesday": {"open": "06:00", "close": "22:00"}, "wednesday": {"open": "06:00", "close": "22:00"}, "thursday": {"open": "06:00", "close": "22:00"}, "friday": {"open": "06:00", "close": "22:00"}, "saturday": {"open": "08:00", "close": "18:00"}, "sunday": {"open": "08:00", "close": "18:00"}}'::jsonb,
  '["eletricidade", "agua", "seguranca24h", "iluminacao", "combustivel_proximo", "manutencao_disponivel"]'::jsonb,
  'Hangar moderno em excelente localização no aeroporto de Congonhas. Ideal para aeronaves executivas e monomotores. Estrutura metálica com piso reforçado.',
  'Acesso 24h mediante agendamento prévio. Estacionamento para visitantes disponível. Próximo à área de abastecimento.',
  true,
  true,
  '[]'::jsonb,
  'active'
),

-- 2. Rio de Janeiro/Galeão
(
  1,
  'SBGL',
  'Rio de Janeiro/Galeão - Antônio Carlos Jobim',
  'Rio de Janeiro',
  'RJ',
  'Brasil',
  'H-7B',
  'Hangar na área de aviação geral, taxiway Echo',
  180.00,
  18.00,
  15.00,
  6.00,
  '["monomotor", "bimotor", "executive", "helicopter"]'::jsonb,
  NULL,
  350.00,
  2100.00,
  7800.00,
  CURRENT_DATE,
  (CURRENT_DATE + INTERVAL '2 years'),
  true,
  '{"monday": {"open": "05:00", "close": "23:00"}, "tuesday": {"open": "05:00", "close": "23:00"}, "wednesday": {"open": "05:00", "close": "23:00"}, "thursday": {"open": "05:00", "close": "23:00"}, "friday": {"open": "05:00", "close": "23:00"}, "saturday": {"open": "06:00", "close": "22:00"}, "sunday": {"open": "06:00", "close": "22:00"}}'::jsonb,
  '["eletricidade", "agua", "seguranca24h", "iluminacao", "wifi", "combustivel_proximo", "manutencao_disponivel", "limpeza"]'::jsonb,
  'Hangar amplo com capacidade para até 2 aeronaves médias ou 3 pequenas. Vista para a Baía de Guanabara. Infraestrutura completa para manutenção preventiva.',
  'FBO no local. Serviços de handling disponíveis. Área climatizada para briefing.',
  true,
  true,
  '[]'::jsonb,
  'active'
),

-- 3. Belo Horizonte/Pampulha
(
  1,
  'SBBH',
  'Belo Horizonte/Pampulha - Carlos Drummond de Andrade',
  'Belo Horizonte',
  'MG',
  'Brasil',
  'H-3',
  'Hangar histórico reformado, próximo ao terminal de passageiros',
  100.00,
  14.00,
  11.00,
  4.80,
  '["monomotor", "bimotor"]'::jsonb,
  NULL,
  200.00,
  1200.00,
  4500.00,
  CURRENT_DATE,
  (CURRENT_DATE + INTERVAL '1 year'),
  true,
  '{"monday": {"open": "07:00", "close": "21:00"}, "tuesday": {"open": "07:00", "close": "21:00"}, "wednesday": {"open": "07:00", "close": "21:00"}, "thursday": {"open": "07:00", "close": "21:00"}, "friday": {"open": "07:00", "close": "21:00"}, "saturday": {"open": "08:00", "close": "18:00"}, "sunday": "closed"}'::jsonb,
  '["eletricidade", "agua", "seguranca24h", "iluminacao", "combustivel_proximo"]'::jsonb,
  'Hangar com arquitetura modernista preservada, localizado no icônico aeroporto da Pampulha. Perfeito para aeronaves clássicas e monomotores.',
  'Aeroporto histórico projetado por Oscar Niemeyer. Acesso controlado. Clube de aviação nas proximidades.',
  false,
  true,
  '[]'::jsonb,
  'active'
),

-- 4. Brasília
(
  1,
  'SBBR',
  'Brasília/Presidente Juscelino Kubitschek',
  'Brasília',
  'DF',
  'Brasil',
  'H-15',
  'Hangar de aviação executiva, terminal privado',
  200.00,
  20.00,
  16.00,
  6.50,
  '["monomotor", "bimotor", "executive", "jet"]'::jsonb,
  NULL,
  450.00,
  2700.00,
  9500.00,
  CURRENT_DATE,
  (CURRENT_DATE + INTERVAL '3 years'),
  true,
  '{"monday": {"open": "00:00", "close": "23:59"}, "tuesday": {"open": "00:00", "close": "23:59"}, "wednesday": {"open": "00:00", "close": "23:59"}, "thursday": {"open": "00:00", "close": "23:59"}, "friday": {"open": "00:00", "close": "23:59"}, "saturday": {"open": "00:00", "close": "23:59"}, "sunday": {"open": "00:00", "close": "23:59"}}'::jsonb,
  '["eletricidade", "agua", "seguranca24h", "iluminacao", "wifi", "ar_condicionado", "combustivel_proximo", "manutencao_disponivel", "limpeza", "sala_reuniao"]'::jsonb,
  'Hangar premium no principal aeroporto do Centro-Oeste. Estrutura de alto padrão com facilidades VIP. Ideal para jatos executivos e aeronaves de grande porte.',
  'Operação 24/7. Acesso direto à pista. Sala de reuniões executivas. Serviço de concierge disponível. Próximo ao terminal de aviação executiva.',
  true,
  true,
  '[]'::jsonb,
  'active'
),

-- 5. Goiânia
(
  1,
  'SBGO',
  'Goiânia/Santa Genoveva',
  'Goiânia',
  'GO',
  'Brasil',
  'H-9',
  'Hangar na área de aviação agrícola, fácil acesso',
  150.00,
  16.00,
  13.00,
  5.00,
  '["monomotor", "bimotor", "agricola"]'::jsonb,
  NULL,
  180.00,
  1000.00,
  3800.00,
  CURRENT_DATE,
  (CURRENT_DATE + INTERVAL '1 year'),
  true,
  '{"monday": {"open": "06:00", "close": "20:00"}, "tuesday": {"open": "06:00", "close": "20:00"}, "wednesday": {"open": "06:00", "close": "20:00"}, "thursday": {"open": "06:00", "close": "20:00"}, "friday": {"open": "06:00", "close": "20:00"}, "saturday": {"open": "07:00", "close": "17:00"}, "sunday": "closed"}'::jsonb,
  '["eletricidade", "agua", "seguranca", "iluminacao", "combustivel_proximo", "lavagem", "area_carregamento"]'::jsonb,
  'Hangar robusto ideal para aviação agrícola e utilitária. Piso reforçado para suportar produtos químicos. Área ampla para manobras.',
  'Próximo à oficina de manutenção especializada em agrícolas. Área de lavagem externa. Estacionamento para veículos de apoio.',
  false,
  true,
  '[]'::jsonb,
  'active'
)
ON CONFLICT DO NOTHING;
