name: Feature Request
description: Suggest a new feature for the Love to Fly Portal
title: "✨ "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out the information below.

  - type: textarea
    id: problem
    attributes:
      label: Problem/Motivation
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I've also thought about...

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which part of the portal would this feature affect?
      options:
        - HangarShare (marketplace)
        - Classifieds
        - Career/Jobs
        - Flight Tools (E6B, planning, etc.)
        - Forum/Community
        - Admin Dashboard
        - User Profile
        - New Feature Area
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my use of the platform)
        - High (would significantly improve my experience)
        - Medium (nice to have)
        - Low (minor enhancement)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case or user story
      placeholder: "As a [role], I want [feature] so that [benefit]"
    validations:
      required: true

  - type: textarea
    id: mockup
    attributes:
      label: Mockups/Examples
      description: If you have mockups, screenshots, or examples from other sites, please share them
      placeholder: Add images or links here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
      placeholder: Any additional information...
