-- Migration: 004_add_missing_user_columns.sql
-- Add missing columns to users table to match application code expectations

ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS cpf VARCHAR(14) UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mobile_phone VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address_zip VARCHAR(10);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address_street VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address_number VARCHAR(10);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address_complement VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address_neighborhood VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address_city VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address_state VARCHAR(2);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address_country VARCHAR(2) DEFAULT 'BR';
ALTER TABLE users ADD COLUMN IF NOT EXISTS aviation_role VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS aviation_role_other VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS social_media JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS newsletter_opt_in BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS terms_agreed BOOLEAN DEFAULT FALSE;