-- Seed Hangar Listings for HangarShare Marketplace
-- Creates diverse hangar properties across Brazilian airports

-- Insert hangar listings linked to owner users
INSERT INTO hangar_listings (
  owner_id, airport_icao, title, description, address,
  hangar_type, size_sqm, max_wingspan_m, max_length_m, max_height_m,
  price_per_month, currency, available, amenities, security_features,
  access_hours, climate_controlled, power_supply, lighting,
  floor_type, door_type, insurance_required, min_rental_period,
  cancellation_policy, location_lat, location_lng, photos,
  views, inquiries, bookings_count, average_rating,
  status, featured, verified, created_at, updated_at
)
SELECT 
  u.id as owner_id,
  listing.airport_icao,
  listing.title,
  listing.description,
  listing.address,
  listing.hangar_type,
  listing.size_sqm,
  listing.max_wingspan_m,
  listing.max_length_m,
  listing.max_height_m,
  listing.price_per_month,
  listing.currency,
  listing.available,
  listing.amenities,
  listing.security_features,
  listing.access_hours,
  listing.climate_controlled,
  listing.power_supply,
  listing.lighting,
  listing.floor_type,
  listing.door_type,
  listing.insurance_required,
  listing.min_rental_period,
  listing.cancellation_policy,
  listing.location_lat,
  listing.location_lng,
  listing.photos,
  listing.views,
  listing.inquiries,
  listing.bookings_count,
  listing.average_rating,
  listing.status,
  listing.featured,
  listing.verified,
  listing.created_at,
  listing.updated_at
FROM users u
CROSS JOIN LATERAL (
  VALUES
    -- Roberto Costa's listings (Aircraft Owner)
    (
      'roberto.costa@test.local',
      'SBSP',
      'Hangar Premium - Congonhas Airport',
      'Hangar espaçoso no Aeroporto de Congonhas, ideal para jatos executivos. Localização privilegiada com fácil acesso às pistas. Climatizado, segurança 24h, e acabamento de alto padrão. Perfeito para proprietários que valorizam conveniência e qualidade.',
      'Av. Washington Luís, s/n - Vila Congonhas, São Paulo - SP, 04626-911',
      'private',
      250.0,
      18.5,
      16.0,
      5.5,
      25000.00,
      'BRL',
      true,
      ARRAY['Climatização', 'WiFi', 'Escritório', 'Área de Descanso', 'Ferramentas', 'Ponto de Combustível', 'Lavagem de Aeronaves'],
      ARRAY['Vigilância 24/7', 'Câmeras de Segurança', 'Controle de Acesso Biométrico', 'Alarme', 'Iluminação Externa'],
      '24/7',
      true,
      '380V Trifásico',
      'LED Full Coverage',
      'Epoxy Industrial',
      'Bi-fold Automática',
      true,
      6,
      '30 dias de antecedência para cancelamento',
      -23.6262,
      -46.6561,
      ARRAY[
        '/seed-assets/hangars/hangar-1.svg',
        '/seed-assets/hangars/hangar-2.svg',
        '/seed-assets/hangars/hangar-3.svg'
      ],
      342,
      28,
      5,
      4.8,
      'active',
      true,
      true,
      NOW() - INTERVAL '6 months',
      NOW() - INTERVAL '2 days'
    ),
    (
      'roberto.costa@test.local',
      'SBGR',
      'Hangar Corporativo - Guarulhos GRU',
      'Hangar de grandes dimensões no maior aeroporto da América Latina. Capacidade para aeronaves widebody. Infraestrutura completa para manutenção. Ideal para operações corporativas de grande porte.',
      'Rod. Hélio Smidt, s/n - Guarulhos - SP, 07190-100',
      'commercial',
      450.0,
      24.0,
      22.0,
      7.0,
      45000.00,
      'BRL',
      true,
      ARRAY['Oficina Equipada', 'Escritório Executivo', 'Sala de Reuniões', 'Cozinha', 'Banheiros', 'Estacionamento 20 vagas', 'Rampa de Acesso'],
      ARRAY['Segurança Aeroportuária', 'Câmeras HD', 'Portão Eletrônico', 'Cerca Perimetral', 'Iluminação LED'],
      '24/7',
      false,
      '380V Trifásico + Gerador',
      'LED Industrial',
      'Concreto Polido',
      'Sliding Hydraulic',
      true,
      12,
      '60 dias de antecedência, multa de 2 meses',
      -23.4356,
      -46.4731,
      ARRAY[
        '/seed-assets/hangars/hangar-4.svg',
        '/seed-assets/hangars/hangar-5.svg'
      ],
      567,
      45,
      8,
      4.9,
      'active',
      true,
      true,
      NOW() - INTERVAL '1 year',
      NOW() - INTERVAL '5 days'
    ),
    
    -- Ana Ferreira's listings (Aircraft Owner)
    (
      'ana.ferreira@test.local',
      'SBJD',
      'Hangar Executivo - Jundiaí Airport',
      'Hangar moderno e funcional em aeroporto executivo de Jundiaí. Excelente para aviação geral e jatos leves. Ambiente tranquilo, longe do tráfego intenso. Boa relação custo-benefício.',
      'Aeroporto de Jundiaí - Jundiaí - SP, 13214-525',
      'private',
      180.0,
      15.0,
      14.0,
      5.0,
      12000.00,
      'BRL',
      true,
      ARRAY['WiFi', 'Escritório Pequeno', 'Ferramentas Básicas', 'Estacionamento', 'Água/Energia'],
      ARRAY['Vigilância Diurna', 'Câmeras', 'Portão Eletrônico', 'Cerca'],
      '06:00-22:00',
      false,
      '220V Monofásico',
      'LED Básico',
      'Concreto',
      'Bi-fold Manual',
      false,
      3,
      '15 dias de antecedência',
      -23.1817,
      -46.9439,
      ARRAY[
        '/seed-assets/hangars/hangar-6.svg'
      ],
      189,
      15,
      3,
      4.5,
      'active',
      false,
      true,
      NOW() - INTERVAL '4 months',
      NOW() - INTERVAL '10 days'
    ),
    (
      'ana.ferreira@test.local',
      'SBKP',
      'Hangar Compartilhado - Campinas Viracopos',
      'Espaço compartilhado em hangar de grandes dimensões. Ideal para quem busca economia sem abrir mão de segurança e infraestrutura. Perfeito para aeronaves leves e médias.',
      'Aeroporto Internacional de Viracopos - Campinas - SP, 13055-900',
      'shared',
      80.0,
      12.0,
      11.0,
      4.5,
      5500.00,
      'BRL',
      true,
      ARRAY['WiFi Compartilhado', 'Banheiro', 'Estacionamento', 'Segurança'],
      ARRAY['Vigilância 24h', 'Câmeras', 'Controle de Acesso'],
      '24/7',
      false,
      '220V',
      'LED',
      'Concreto',
      'Compartilhada',
      true,
      1,
      '7 dias de antecedência',
      -23.0074,
      -47.1344,
      ARRAY[
        '/seed-assets/hangars/hangar-7.svg'
      ],
      234,
      22,
      7,
      4.3,
      'active',
      false,
      true,
      NOW() - INTERVAL '2 months',
      NOW() - INTERVAL '1 day'
    ),
    
    -- Additional listings from test users
    (
      'paulo.martins@test.local',
      'SBMT',
      'Hangar com Oficina - Campo de Marte',
      'Hangar com oficina completa para manutenção. Ideal para mecânicos ou proprietários que fazem própria manutenção. Ferramentas e equipamentos inclusos. Ambiente de trabalho profissional.',
      'Av. Olavo Fontoura, 1078 - Santana, São Paulo - SP, 02012-021',
      'maintenance',
      200.0,
      14.0,
      13.0,
      4.8,
      15000.00,
      'BRL',
      true,
      ARRAY['Oficina Completa', 'Ferramentas Profissionais', 'Compressor de Ar', 'Elevador Hidráulico', 'Bancada', 'Armários', 'WiFi'],
      ARRAY['Vigilância', 'Câmeras', 'Alarme', 'Extintor'],
      '06:00-20:00',
      false,
      '220V/380V',
      'LED Industrial',
      'Epoxy',
      'Rolling Door',
      false,
      6,
      '30 dias de antecedência',
      -23.5086,
      -46.6377,
      ARRAY[
        '/seed-assets/hangars/hangar-8.svg',
        '/seed-assets/hangars/hangar-9.svg'
      ],
      156,
      12,
      2,
      4.7,
      'active',
      false,
      true,
      NOW() - INTERVAL '5 months',
      NOW() - INTERVAL '15 days'
    ),
    
    -- More listings from other users
    (
      'fernanda.lima@test.local',
      'SBRJ',
      'Hangar Compacto - Santos Dumont',
      'Hangar compacto no icônico Aeroporto Santos Dumont. Localização central no Rio de Janeiro. Perfeito para aeronaves monomotoras. Vista privilegiada da Baía de Guanabara.',
      'Praça Senador Salgado Filho, s/n - Centro, Rio de Janeiro - RJ, 20021-340',
      'private',
      120.0,
      11.0,
      10.0,
      4.0,
      18000.00,
      'BRL',
      false,
      ARRAY['WiFi', 'Energia', 'Água', 'Vista para Baía'],
      ARRAY['Segurança Aeroporto', 'Câmeras', 'Cerca'],
      '06:00-22:00',
      false,
      '220V',
      'LED',
      'Concreto',
      'Bi-fold',
      true,
      6,
      '45 dias de antecedência',
      -22.9099,
      -43.1634,
      ARRAY[
        '/seed-assets/hangars/hangar-10.svg'
      ],
      412,
      35,
      12,
      4.6,
      'rented',
      false,
      true,
      NOW() - INTERVAL '8 months',
      NOW() - INTERVAL '3 months'
    ),
    
    (
      'lucas.almeida@test.local',
      'SBSP',
      'Box Econômico - Congonhas',
      'Box individual econômico para aeronaves pequenas. Segurança básica mas eficiente. Ótimo custo-benefício para estudantes e iniciantes.',
      'Av. Washington Luís, s/n - Congonhas, São Paulo - SP',
      'tie-down',
      40.0,
      10.0,
      9.0,
      3.5,
      3500.00,
      'BRL',
      true,
      ARRAY['Energia', 'Segurança Básica'],
      ARRAY['Vigilância', 'Cerca'],
      '24/7',
      false,
      '110V',
      'Básica',
      'Asfalto',
      'Sem Porta',
      false,
      1,
      '7 dias',
      -23.6266,
      -46.6564,
      ARRAY[
        '/seed-assets/hangars/hangar-11.svg'
      ],
      89,
      8,
      4,
      4.1,
      'active',
      false,
      false,
      NOW() - INTERVAL '1 month',
      NOW() - INTERVAL '5 days'
    ),
    
    -- International/Premium listings
    (
      'michael.johnson@test.local',
      'SBGR',
      'Premium Hangar - Wide Body Capable',
      'Estado-da-arte hangar facility for widebody executive jets. Climate controlled, full maintenance capabilities, and concierge services. The ultimate in aircraft storage.',
      'Rod. Hélio Smidt - Guarulhos International - SP',
      'luxury',
      600.0,
      36.0,
      30.0,
      8.0,
      85000.00,
      'BRL',
      true,
      ARRAY['Full Climate Control', 'Executive Lounge', 'Conference Room', 'Concierge Service', 'Catering Kitchen', 'Crew Rest Area', 'VIP Parking', 'Detailing Services'],
      ARRAY['Military Grade Security', '4K Cameras', 'Biometric Access', 'Armed Guards', 'Perimeter Sensors'],
      '24/7/365',
      true,
      '600A Three-Phase + Backup',
      'Smart LED System',
      'Premium Epoxy',
      'Automated Hydraulic Doors',
      true,
      12,
      '90 days notice, 3 months penalty',
      -23.4321,
      -46.4698,
      ARRAY[
        '/seed-assets/hangars/hangar-12.svg',
        '/seed-assets/hangars/hangar-13.svg',
        '/seed-assets/hangars/hangar-14.svg'
      ],
      891,
      67,
      15,
      5.0,
      'active',
      true,
      true,
      NOW() - INTERVAL '3 months',
      NOW()
    ),
    
    -- Regional airports
    (
      'carlos.silva@test.local',
      'SBPA',
      'Hangar Salgado Filho - Porto Alegre',
      'Hangar em localização estratégica no Sul do país. Ideal para operações regionais. Infraestrutura completa e preço justo.',
      'Av. dos Estados - Porto Alegre - RS',
      'commercial',
      280.0,
      20.0,
      18.0,
      6.0,
      20000.00,
      'BRL',
      true,
      ARRAY['Oficina', 'Escritório', 'WiFi', 'Estacionamento', 'Segurança'],
      ARRAY['Vigilância 24h', 'Câmeras', 'Alarme'],
      '24/7',
      false,
      '380V',
      'LED',
      'Concreto',
      'Sliding',
      true,
      6,
      '30 dias',
      -29.9939,
      -51.1714,
      ARRAY[
        '/seed-assets/hangars/hangar-15.svg'
      ],
      223,
      19,
      6,
      4.4,
      'active',
      false,
      true,
      NOW() - INTERVAL '7 months',
      NOW() - INTERVAL '20 days'
    ),
    
    (
      'maria.santos@test.local',
      'SBCF',
      'Hangar Tancredo Neves - Confins BH',
      'Hangar moderno em Belo Horizonte. Excelente acesso e infraestrutura. Preço competitivo para a região Sudeste.',
      'Rodovia MG-010 - Confins - MG',
      'commercial',
      320.0,
      22.0,
      20.0,
      6.5,
      28000.00,
      'BRL',
      true,
      ARRAY['Climatização Parcial', 'Escritório', 'Sala de Briefing', 'WiFi', 'Cozinha', 'Estacionamento'],
      ARRAY['Segurança Aeroporto', 'Câmeras HD', 'Controle de Acesso', 'Vigilância'],
      '24/7',
      true,
      '380V + Backup',
      'LED Full',
      'Epoxy',
      'Hydraulic Bi-fold',
      true,
      12,
      '60 dias de antecedência',
      -19.6244,
      -43.9719,
      ARRAY[
        '/seed-assets/hangars/hangar-16.svg',
        '/seed-assets/hangars/hangar-17.svg'
      ],
      445,
      38,
      10,
      4.8,
      'active',
      true,
      true,
      NOW() - INTERVAL '9 months',
      NOW() - INTERVAL '7 days'
    )
) AS listing(
  owner_email, airport_icao, title, description, address,
  hangar_type, size_sqm, max_wingspan_m, max_length_m, max_height_m,
  price_per_month, currency, available, amenities, security_features,
  access_hours, climate_controlled, power_supply, lighting,
  floor_type, door_type, insurance_required, min_rental_period,
  cancellation_policy, location_lat, location_lng, photos,
  views, inquiries, bookings_count, average_rating,
  status, featured, verified, created_at, updated_at
)
WHERE u.email = listing.owner_email

ON CONFLICT DO NOTHING;

-- Output summary
SELECT 'Hangar listings seeded successfully!' as message,
       COUNT(*) as total_listings,
       COUNT(*) FILTER (WHERE status = 'active') as active_listings,
       COUNT(*) FILTER (WHERE status = 'rented') as rented_listings,
       COUNT(*) FILTER (WHERE featured = true) as featured_listings,
       SUM(views) as total_views,
       SUM(inquiries) as total_inquiries,
       SUM(bookings_count) as total_bookings
FROM hangar_listings;
